module.exports = {
  root: true,
  parser: "@typescript-eslint/parser",
  plugins: ["@typescript-eslint", "deprecate"],
  extends: [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:react/recommended",
  ],
  rules: {
    "@typescript-eslint/no-unused-vars": [
      "warn",
      {
        vars: "all",
        args: "all",
        caughtErrors: "all",
        varsIgnorePattern: "^_",
        argsIgnorePattern: "^_",
        caughtErrorsIgnorePattern: "^_",
        ignoreRestSiblings: true,
      },
    ],
    "@typescript-eslint/explicit-module-boundary-types": "off",
    "@typescript-eslint/ban-ts-comment": "off",
    "@typescript-eslint/no-empty-function": "off",
    "@typescript-eslint/no-explicit-any": "off",
    "@typescript-eslint/ban-types": "warn",
    "react/prop-types": "off",

    eqeqeq: "warn",
    "react/jsx-key": "warn",
    "no-case-declarations": "warn",
    "no-prototype-builtins": "warn",
    "react/no-find-dom-node": "warn",
    "no-useless-escape": "warn",
    "no-useless-catch": "warn",
    "no-constant-condition": "warn",
    "react/no-children-prop": "warn",
    "no-empty": "warn",
    "no-fallthrough": "warn",
    "react/display-name": "warn",
    "@typescript-eslint/adjacent-overload-signatures": "warn",
    "react/no-unescaped-entities": "warn",
    "@typescript-eslint/no-var-requires": "warn",
    "@typescript-eslint/no-non-null-asserted-optional-chain": "warn",
    "@typescript-eslint/no-namespace": "warn",
    "no-irregular-whitespace": "warn",
    "react/jsx-no-target-blank": "warn",

    "deprecate/import": ["error", { name: "moment", use: "date-fns" }],

    "padding-line-between-statements": [
      "warn",
      {
        blankLine: "always",
        prev: "*",
        next: [
          "if",
          "switch",
          "do",
          "for",
          "while",
          "throw",
          "try",
          "with",
          "function",
          "iife",
          "class",
          "break",
          "continue",
          "return",
          "debugger",
          "import",
          "export",
          "var",
          "let",
          "const",
          "block",
          "block-like",
          "multiline-block-like",
          "empty",
          "directive",
          "expression",
        ],
      },
      {
        blankLine: "always",
        prev: [
          "if",
          "switch",
          "do",
          "for",
          "while",
          "throw",
          "try",
          "with",
          "function",
          "iife",
          "class",
          "break",
          "continue",
          "return",
          "debugger",
          "import",
          "export",
          "var",
          "let",
          "const",
          "block",
          "block-like",
          "multiline-block-like",
          "empty",
          "directive",
          "expression",
        ],
        next: "*",
      },

      { blankLine: "never", prev: "case", next: "case" },

      { blankLine: "any", prev: "iife", next: "iife" },
      { blankLine: "any", prev: "import", next: "import" },
      { blankLine: "any", prev: "export", next: "export" },
      { blankLine: "any", prev: "var", next: "var" },
      { blankLine: "any", prev: "let", next: "let" },
      { blankLine: "any", prev: "const", next: "const" },
      { blankLine: "any", prev: "block", next: "block" },
      { blankLine: "any", prev: "empty", next: "empty" },
      { blankLine: "any", prev: "directive", next: "directive" },
      { blankLine: "any", prev: "expression", next: "expression" },

      {
        blankLine: "any",
        prev: ["block-like", "multiline-block-like"],
        next: ["block-like", "multiline-block-like"],
      },
    ],
  },
  settings: {
    react: {
      version: "16.8.6",
    },
  },
};
